### ISSUE TITLE
Fix respawn issues

### ISSUE THREAD

**Issue by mcrowder65** [mcrowder65/first-person-shooter#34]
- [ ] somehow health will sometimes not be full when respawning
- [ ] set rotation
- [x] velocity carries over

**Comment by seattleite7** [comment]
I'm not experiencing velocity bugs after killcam.

**Comment by seattleite7** [comment]
Not experiencing health problems.

I AM experiencing some problems with the camera rotation being screwed up after respawning. It is usually screwed up in the horizontal direction.
