### ISSUE TITLE
Killcam stuck in infinite loop

### ISSUE THREAD

**Issue by mcrowder65** [mcrowder65/first-person-shooter#36]
https://drive.google.com/open?id=0BxYl7lEbWcxrbHRBQWlMbTd6MEU

- [ ] also happens when falling into water on hearth. assuming it's because that's essentially a fall off map issue.

**Comment by mcrowder65** [comment]
This happened when i jumped off the map on a client

**Comment by seattleite7** [comment]
cannot reproduce, potentially fixed

**Comment by mcrowder65** [comment]
@seattleite7 have you pushed anything? I don't see a difference. Be sure to test this on a client.
